---
defaults:
  - _self_
  - parameters.yaml
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Hydra specific
# TODO: Add help message, see: https://hydra.cc/docs/configure_hydra/app_help/ 
hydra:
  help:
    template:
      'TODO: Add help message'
  run:
    dir:
      outputs/generate_output/${now:%Y-%m-%d_%H-%M-%S}_${output_dir}

  sweeper:
    params:
      parameters.MDPP: 84, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 200
      parameters.vevD: 0.1, 0.5, 1.0
  
  sweep:
    dir: multirun/${now:%Y-%m-%d}_${process.model}
    subdir: ${hydra.job.num}_MDPP_${parameters.MDPP}_vevD_${parameters.vevD}

madgraph_dir: MG5_aMC_v3_4_1                                                                    # location of MadGraph directory (relative to repo)
transfer_dir: /eos/user/b/bewilson/typeII_generation/${process.model}_generation                # location so save output files
output_dir: ${transfer_dir}/${process.model}_MDPP_${parameters.MDPP}_vevD_${parameters.vevD}    # MadGraph output directory

batch: False                                                        # run on htc batch system
debug: False                                                        # run, but don't run MadGraph or submit batch jobs
