---
# Hydra specific config settings
defaults:
  - _self_
  - parameters.yaml                            # You can add additional config files here             
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# TODO: Add help message, see: https://hydra.cc/docs/configure_hydra/app_help/ 
hydra:
  help:
    template:
      'TODO: Add help message'
  
  # single run settings
  run:
    dir:
      generate_output/${now:%Y-%m-%d_%H-%M-%S}_${process.output_dir}

  # multirun settings
  sweeper:
    params:
      parameters.MDPP: 84, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 200, 800, 1000, 1200, 1400, 1600, 1800, 2000
      parameters.vevD: 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 0, 0.1, 0.5, 1.0
  
  sweep:
    dir: multirun/${now:%Y-%m-%d}_${process.model}
    subdir: ${process.output_dir}

# Other settings
madgraph_dir: MG5_aMC_v3_4_1                                 # location of MadGraph directory (relative to repo)

batch: False                                                 # run on htc batch system
debug: False                                                 # run, but don't run MadGraph or submit batch jobs

# Transfer output (only when running in batch mode)
transfer_files: True                                         # Location to transfer MG production dir after generation       
cleanup: True                                                # Delete all the rubbish from the MG production dir
transfer_dir: /eos/user/b/bewilson/generate_output/${now:%Y-%m-%d_%H-%M-%S}_${process.process_name}   # location so save output files