--- 
parameters:

 # TypeII seesaw 'Richard & co.'
 # See: https://arxiv.org/abs/1912.08975
  log10_vevD: -7  # Use log10(vevD) since it make it easier to do range based scans with hydra
  MD0: 500
  MDP: 503
  MDPP: 502
  WD0: 'auto' 
  WDP: 'auto' 
  WDPP: 'auto' 

  # TypeII seesaw 'otherM'
  # See: https://arxiv.org/abs/1105.1925
  #      https://arxiv.org/abs/1911.00971
  MH2: 500
  MA0: 500
  MHP: 500
  MH2P: 500
  log10_vevT: -3
  
  # HeavyN
  mN1: 50000
  mN2: 50000
  mN3: 500
  VtaN1: 0
  VtaN2: 0
  VtaN3: 1

  # Common
  nevents:  10000
  dummy: 0 # For testing

