--- 
parameters:
  log10_vevD: -7  # Use log10(vevD) since it make it easier to do range based scans with hydra
  MD0: 500
  MDP: 503
  MDPP: 502
  WD0: 'auto' 
  WDP: 'auto' 
  WDPP: 'auto' 
  nevents:  10000
