---
model: TypeII_NLO_v1_2_UFO            # See: https://arxiv.org/abs/1912.08975

process_name: typeII_single_prod_WWjj

output_dir: ${process.process_name}_${parameters.MDPP}_${parameters.vevD}

gen_cmd: ['import model ${process.model}',
          'generate d++ > w+ w+',
          'add process d-- > w- w-',
          'output ${process.output_dir}',
          'launch ',
          'shower=pythia8',
          'set vevd: ${parameters.vevD}',
          'set MD0 5000',
          'set MDP 5000',
          'set MDPP ${parameters.MDPP}',
          'set WD0 ${parameters.WD0}',
          'set WDP ${parameters.WDP}',
          'set WDPP ${parameters.WDPP}',
          'set lamHD1 1.0',
          'set lamD1 1.0',
          'set nevents ${parameters.nevents}'
          ]

          # NOTE: setting MD0 = MDP = MDPP on purpose to simplfy things
          # NOTE: lamHD1 1.0 = lamD1 1.0 = 1 like in paper (also how J&L did things)
