---
model: Standard_Model

process_name: SM_ssWW_EWK

output_dir: ${process.process_name}

gen_cmd: ['generate p p > w+ w+ j j QCD=0 QED==6',
          'add process p p > w- w- j j QCD=0 QED==6',
          'output ${process.output_dir}',
          'launch ',
          'shower=pythia8',
          ]
