---
# see https://gitlab.cern.ch/atlas-physics/pmg/mcjoboptions/-/blob/master/500xxx/500991/mc.MGH7EG_LO_INT_ssWWjj.py

model: Standard_Model

process_name: SM_ssWW_INT

output_dir: madevent

rivet: minimal_2l2j

dsid: 500988
