---
# see https://gitlab.cern.ch/atlas-physics/pmg/mcjoboptions/-/blob/master/500xxx/500991/mc.MGH7EG_LO_INT_ssWWjj.py

model: Standard_Model

process_name: SM_ssWW_INT

output_dir: SM_ssWW_INT

rivet: minimal_2l2j

gen_cmd: ['define l+ e+ mu+ ta+',
          'define l- e- mu- ta-',
          'define v ve vm vt',
          'define v~ ve~ vm~ vt~ ',
          'generate p p > l+ vl l+ vl j j QCD^2==2 @1',
          'add process p p > l- vl~ l- vl~ j j QCD^2==2 @1',
          'output ${process.process_name}',
          'launch',
          'shower=pythia8',
          'set sde_strategy 1', # These options really help improve event yield
          'set hard_survey 1',
          ]