---
model: Standard_Model

process_name: SM_ssWW_EWK

output_dir: ${process.process_name}

gen_cmd: ['generate p p > w+ w+ j j QCD=0',
          'add process p p > w- w- j j QCD=0',
          'output ${process.output_dir}',
          'launch',
          'shower=pythia8',
          'set nevents ${parameters.nevents}'
          ]
