---
# see https://gitlab.cern.ch/atlas-physics/pmg/mcjoboptions/-/blob/master/500xxx/500991/mc.MGH7EG_LO_INT_ssWWjj.py

model: Standard_Model

process_name: SM_ssWW_EWK

output_dir: madevent # Note, when generating official dsids this is the name of the output dir

rivet: minimal_2l2j

dsid: 500986
