---
# see https://gitlab.cern.ch/atlas-physics/pmg/mcjoboptions/-/blob/master/500xxx/500991/mc.MGH7EG_LO_INT_ssWWjj.py

model: Standard_Model

process_name: SM_ssWW_EWK

output_dir: SM_ssWW_EWK # Note, when generating official dsids this is the name of the output dir

rivet: minimal_2l2j

gen_cmd: [
          'generate p p > ta+ ta+ vt vt j j QED==6 QCD=0 @1',
          'add process p p > ta- ta- vt~ vt~ j j QED==6 QCD=0 @1',
          'output ${process.process_name}',
          'launch',
          'shower=pythia8',
          'set sde_strategy 1', # These options really help improve event yield
          'set hard_survey 1',
          ]
