---
model: Standard_Model

process_name: SM_ssWW_INT

output_dir: ${process.process_name}

rivet: minimal_2l2j

gen_cmd: ['define l+ = e+ mu+ ta+',
          'define vl = ve vm vt',
          'define l- = e- mu- ta-',
          'define vl~ = ve~ vm~ vt~',
          'define p = g u c d s u~ c~ d~ s~ b b~',
          'define j = g u c d s u~ c~ d~ s~ b b~',
          'generate p p > l+ vl l+ vl j j QCD^2==2 @1',
          'add process p p > l- vl~ l- vl~ j j QCD^2==2 @1',
          'output ${process.output_dir}',
          'launch',
          'shower=pythia8',
          'set nevents ${parameters.nevents}'
          ]
