---
model: TypeII_NLO_v1_2_UFO              # See: https://arxiv.org/abs/1912.08975

process_name: double_production_inclusive

output_dir: ${process.process_name}_${parameters.MDPP}_${parameters.log10_vevD}

rivet: minimal_2l2j

gen_cmd: ['import model ${process.model}',
          'generate p p > d++ d--',
          'output ${process.output_dir}',
          'launch ',
          'shower=pythia8',
          'set vevd ${eval: "10**${parameters.log10_vevD}"}',
          'set MD0 ${parameters.MDPP}',
          'set MDP ${parameters.MDPP}',
          'set MDPP ${parameters.MDPP}',
          'set WD0 ${parameters.WD0}',
          'set WDP ${parameters.WDP}',
          'set WDPP ${parameters.WDPP}',
          'set lamHD1 1.0',
          'set lamD1 1.0',
          'set nevents ${parameters.nevents}'
          ]

          # NOTE: setting MD0 = MDP = MDPP on purpose to simplfy things
          # NOTE: lamHD1 1.0 = lamD1 1.0 = 1 like in paper (also how J&L did things)
