---
# R. Ruiz
# 2023 April 
###############################
## Z > l l* > l l Dpp* >  4l ##
###############################

model: TypeII_NLO_v1_2_UFO              # See: https://arxiv.org/abs/1912.08975

process_name: typeII_Z4l

output_dir: '${process.process_name}_${parameters.MDPP}_${parameters.vevD}}'

rivet: minimal_2l2j


gen_cmd: [
          'import model TypeII_NLO_v1_2_UFO',
          'generate    z > e+ e+ mu- mu- QED=3 QCD=0',
          'add process z > e- e- mu+ mu+ QED=3 QCD=0',
          'output ${process.output_dir}',
          'launch TypeII_Z_4lep_ssElEl_ssMuMu',
          'shower=pythia8',
          'set vevd ${eval: "10**${parameters.log10_vevD}"}',
          'set MD0 ${parameters.MDPP}',
          'set MDP ${parameters.MDPP}',
          'set MDPP ${parameters.MDPP}',
          'set WD0 ${parameters.WD0}',
          'set WDP ${parameters.WDP}',
          'set WDPP ${parameters.WDPP}',
          'set lamHD1 1.0',
          'set lamD1 1.0',
          'set nevents ${parameters.nevents}',
          'set no_parton_cut',
        ]
