---
model: TypeII_Seesaw_UFO

process_name: single_production_inclusive_otherM

output_dir: '${process.process_name}_${parameters.MH2P}_${eval: "10**${parameters.log10_vevT}"}'

rivet: minimal_2l2j

gen_cmd: ['import model ${process.model}',
          'generate p p > h++ j j',
          'add process p p > h-- j j',
          'output ${process.output_dir}',
          'launch',
          'shower=pythia8',
          'set vevT ${eval: "10**${parameters.log10_vevT}"}',
          'set MH2 ${parameters.MH2P}',
          'set MA0 ${parameters.MH2P}',
          'set MHP ${parameters.MH2P}',
          'set MH2P ${parameters.MH2P}',
          'set WH2 auto',
          'set WA0 auto',
          'set WHP auto',
          'set WH2P auto',
          'set nevents ${parameters.nevents}'
          ]